### ISSUE TITLE
Replication Test

### ISSUE THREAD

**Issue by ghost** [comp413-2017/RDFS#18]
Come to a conclusion about Replication Test 

why does it fail?
identify replication issues and open new issue for fixing it separate from fixing test.

**Comment by rzhang0720** [comment]
After reviewing ReplicationTest, I found that the main reason causing ReplicationTest to fail was in the way that the test was creating multiple data nodes. It was not calling the correct command-line arguments to create data nodes on different ports, and was instead creating the same data node multiple times.

If multiple data nodes are created and changes to RDFS are made, these changes are reflected across all of the data nodes. This behavior is identifiable by creating the data nodes, putting a file into RDFS, killing all but 1 of the data nodes, and then trying to access the file within RDFS again.

It is worth noting, however, that this test does not pass in the case where multiple (3) data nodes are created, a file is placed in RDFS, a new data node (4) is created, the original 3 data nodes are removed, and a user tries to access the created file from the 1 remaining data node. If this is the expected replication behavior of RDFS, then this functionality does not work.
