### ISSUE TITLE
ReadWrite Test

### ISSUE THREAD

**Issue by ghost** [comp413-2017/RDFS#19]
come to a conclusion about ReadWrite test

why does it fail on CI ?
fix the test on CI or remove it from CI script.

**Comment by ghost** [comment]
this is fixed by copying the test setup from replication test.

**Comment by LINKIWI** [comment]
Nice work, what was the root cause of the local-CI discrepancy? Is there an PR open that fixes this?

**Comment by ghost** [comment]
[here is the PR with some details](https://github.com/comp413-2017/RDFS/pull/40)
