### ISSUE TITLE
fix all lint errors

### ISSUE THREAD

**Issue by ghost** [comp413-2017/RDFS#23]
fix all lint errors according to cpplint
https://github.com/cpplint/cpplint

**Comment by LINKIWI** [comment]
I'll fix the ones in the first two source directories `native-filesystem` and `rice-datanode`

**Comment by ghost** [comment]
I'll take namenode, rpcserver, and test. That leaves zkwrapper and zookeeper for anant

**Comment by ananttibrewal** [comment]
Sounds good! I'll start working on zkwrapper and zookeeper.
