### ISSUE TITLE
Deletion: one timing benchmark and one unit test implemented

### ISSUE THREAD

**Issue by evi-liu** [comp413-2017/RDFS#43]

**Comment by jeffreyxiong** [comment]
Implemented 5 correctness tests for Listing: **deleteBasicFile**, **deleteEmptyDirectory**, **deleteDirectory**, **deleteNonExistantFile**, and **deleteNestedNonExistantFile**. These tests are located in `test/namenode/DeletionTest.cc` on branch `feature/nn-performance`. Implemented 1 benchmark, also located in `test/namenode/DeletionTest.cc` on branch `feature/nn-performance`.
