### ISSUE TITLE
Listing: one timing benchmark and one unit test implemented

### ISSUE THREAD

**Issue by evi-liu** [comp413-2017/RDFS#44]

**Comment by cannontwo** [comment]
Implemented 3 correctness tests for Listing: **getOneFileListing**, **getMultipleFilesFromDir**, **failToListNonexistentFile**. These tests are located in `test/namenode/ListingTest.cc` on branch `feature/nn-performance`

**Comment by cannontwo** [comment]
Implemented benchmarks specified in the design doc in **listingPerformance**.
