### ISSUE TITLE
Health ZNodes not ephemeral

### ISSUE THREAD

**Issue by evi-liu** [comp413-2017/RDFS#73]

**Comment by cannontwo** [comment]
Basic plan is to remove the default `ephemeral = false` argument for `ZKWrapper::create`, then resolve any improper method calls that are revealed. We know that at least one incorrect call happens in `zk_dn_client.cc`, and that this affects the ability of the NameNode to check if DataNodes are live. I will see if other errors arise once this change is made.

**Comment by cannontwo** [comment]
Made changes, but it appears that the NameNode is not checking the correct nodes within the `/health` hierarchy in zookeeper, so the namenode may still not be aware when DataNodes go down.

**Comment by cannontwo** [comment]
Upon investigation of the logs from running ReplicationTest, it appears that — at least in the tested case — DataNode disconnection is being correctly identified and responded to by pushing previously stored blocks onto other replication queues.

See the attached log for more detail: [out.txt](https://github.com/comp413-2017/RDFS/files/1405925/out.txt)
